version: "3.9"

services:
  rust-web:
    restart: always
    container_name: rust-web_container
    env_file:
      - envs/database.env
      - envs/jenkins.env
      - envs/openai.env
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - 8000:8000
      - 5432:5432
    networks:
      nginx-network:
        ipv4_address: 172.30.0.81


networks:
  nginx-network:
    external: true
    name: nginx-net
    ipam:
      driver: bridge
      config:
        - subnet: 172.30.0.1/16

